
databases:
  - name: mysitedb
    plan: free
    databaseName: mysite
    user: mysite

services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: >
      python manage.py migrate &&
      python -m gunicorn PortfolioProject.asgi:application -k uvicorn.workers.UvicornWorker
    envVars:
      - key: DATABASE_URL
        value: "postgresql://blog_cvcg_user:y45AJMIpcsAcsZ40oFQK9ac1KZc6ZiDC@dpg-cugfiri3esus73feimog-a/blog_cvcg"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
        envVars:
     


