# Generated by Django 5.0.1 on 2025-01-19 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codehistory',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='codehistory',
            name='user',
        ),
    ]
